In [1]:
import torch
import torch.nn as nn
from torch.optim import Adam

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [3]:
input_size = 2
num_layers = 2

In [4]:
a = torch.tensor([[1., 2.], [3., 4.], [5., 6.]])

In [5]:
a.to(device)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], device='cuda:0')

In [6]:
a

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [7]:
input_tensor = torch.tensor([[1., 2.], [3., 4.], [5., 6.]]).to(device)
label_tensor = torch.tensor([[1., 2.], [3., 4.], [5., 6.]]).to(device)

In [8]:
gru = nn.GRU(input_size, 2, num_layers, batch_first=True).to(device)

In [9]:
output, hidden = gru(input_tensor)

print(output.shape)
print(hidden.shape)

torch.Size([3, 2])
torch.Size([2, 2])


In [10]:
criterion = nn.MSELoss().to(device)
optimizer = Adam(gru.parameters())

for _ in range(10000):
    output, hidden = gru(input_tensor)

    loss = criterion(output, label_tensor)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

In [11]:
out, _ = gru(
    torch.tensor([[3., 4.], [5., 6.], [7., 8.]]).to(device)
)

out

tensor([[0.9907, 0.9993],
        [1.0000, 1.0000],
        [1.0000, 1.0000]], device='cuda:0', grad_fn=<SqueezeBackward1>)