In [1]:
import torch
import torch.nn as nn
from torch.optim import Adam

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [3]:
input_size = 2
hidden_size = 2
num_layers = 1

In [4]:
a = torch.tensor([[1., 2.], [3., 4.], [5., 6.]])

In [5]:
a.to(device)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], device='cuda:0')

In [6]:
a

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [7]:
input_tensor = torch.tensor([[[1., 2.], [3., 4.], [5., 6.]]]).to(device)
hidden = torch.zeros(hidden_size)
label_tensor = torch.tensor([[[1., 2.], [3., 4.], [5., 6.]]]).to(device)

In [8]:
class Net(torch.nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(Net, self).__init__()
        self.rnn = torch.nn.GRU(input_size, hidden_size, batch_first=True)
        self.fc = torch.nn.Linear(hidden_size, output_size, bias=True)

    def forward(self, x):
        x, _status = self.rnn(x)
        x = self.fc(x)
        return x

In [9]:
gru = Net(2, 2, 2).to(device)

In [10]:
output = gru(input_tensor)

print(output.shape)
print(hidden.shape)

torch.Size([1, 3, 2])
torch.Size([2])


In [11]:
criterion = nn.MSELoss().to(device)
optimizer = Adam(gru.parameters())

hidden = torch.zeros(hidden_size)
for _ in range(10000):
    output = gru(input_tensor)

    loss = criterion(output, label_tensor)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

In [12]:
out, hidden = gru(
    torch.tensor([[3., 4.], [5., 6.]]).to(device)
)

out, hidden

(tensor([1.2327, 2.3639], device='cuda:0', grad_fn=<UnbindBackward0>),
 tensor([4.5514, 5.5617], device='cuda:0', grad_fn=<UnbindBackward0>))