In [2]:
import torch

In [2]:
torch.tensor(1).view(1, 1, 1, 1)

tensor([[[[1]]]])

In [3]:
t1 = torch.tensor(
    [1., 2., 3.]
).unsqueeze(0)
#t1 = t1.view(1, 1, *t1.shape)

t2 = torch.tensor(
    [
        [1., 2., 3.],
        [4., 5., 6.]
    ]
)
#t2 = t2.view(1, *t2.shape)

t3 = torch.randn(4, 4, 4)

In [4]:
torch.cat((t1, t2))

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [4., 5., 6.]])

In [7]:
t1.shape, t2.shape, t3.shape

(torch.Size([1, 1, 3]), torch.Size([1, 2, 3]), torch.Size([4, 4, 4]))

In [8]:
torch.stack([t1, t2, t3])

RuntimeError: stack expects each tensor to be equal size, but got [1, 1, 3] at entry 0 and [1, 2, 3] at entry 1

In [ ]:
torch.cat((t1, t2, t3), dim=0)

RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 1 but got size 2 for tensor number 1 in the list.

In [14]:
tensor1 = torch.randn(3,3,3)
tensor2 = torch.randn(4,4)

tensor2_pad = torch.zeros(1,4,4)
tensor2_pad[0,:,:] = tensor2

concat_tensor = torch.cat([tensor1, tensor2_pad], dim=0)


RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 3 but got size 4 for tensor number 1 in the list.

In [15]:
t1 = torch.zeros(3, 3)
t2 = torch.tensor([[1, 2, 3], [1, 2, 3]])
t1[:t2.shape[0], :] = t2
t1

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [0., 0., 0.]])