박수빈

In [1]:
from tqdm.notebook import tqdm

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

import torch
import torch.nn as nn
import torch.functional as F
from torch.utils.data import Dataset, DataLoader

2023-01-18 19:34:33.689328: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-18 19:34:34.382654: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-01-18 19:34:34.382738: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-01-18 19:34:34.382744: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nv

In [ ]:
torch.autograd.set_detect_anomaly(True)

In [ ]:
from scipy.spatial.distance import cosine

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [2]:
df = pd.DataFrame(
    {
        'a': [1, 2, 3],
        'b': [4, 5, 6]
    }
)

In [6]:
index = np.random.randint(0, 10, size=5)
index

array([3, 2, 6, 3, 8])

In [3]:
import random

# Get a random index
index = random.randint(0, len(df) - 1)

# Get the row at the random index
print(df.iloc[index])


a    3
b    6
Name: 2, dtype: int64


## PyTorch Syntax

In [ ]:
model = nn.Linear(in_features=1, out_features=1)

x_data = torch.Tensor([1, 2, 3, 4, 5]).view(-1, 1)
y_data = torch.Tensor([2, 4, 6, 8, 10]).view(-1, 1)

criterion = nn.MSELoss(model.parameters())
optimizer = torch.optim.Adam()

for _ in range(100):
    pred = model(x_data)
    loss = criterion(pred, y_data)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

[Parameter containing:
tensor([[-0.8512]], requires_grad=True), Parameter containing:
tensor([-0.5640], requires_grad=True)]
